### ISSUE TITLE
Falta documentación

### ISSUE THREAD

**Issue by cr0hn** [UVaNoobs/BlueFingerprint#1]
El proyecto no tiene ningún tipo de documentación

**Comment by UVaNoobs** [comment]
Nos gustaría que se especificase un poco más sobre la mejora sugerida "Falta documentación".
 ¿Tiene ésta relación con el issue propuesto"Buenas prácticas para proyectos OSS"?

Gracias de antemano.

**Comment by cr0hn** [comment]
Más allá de explicar el objetivo del proyecto, como parte de la documentación es necesario que expliquéis: cómo funciona, instalación, como arrancarlo, salida de datos, configuración...
