### ISSUE TITLE
Código copiado de StackOverflow

### ISSUE THREAD

**Issue by cybercamphackathon** [UVaNoobs/BlueFingerprint#4]
https://www.goodreads.com/book/show/29437996-copying-and-pasting-from-stack-overflow

https://github.com/UVaNoobs/BlueFingerprint/blob/0b8025ac0f59ed1fa41d5634cd67c73f1877f735/MainActivity.java#L241

Por favor, si reutilizais código disponible en Internet, poned la referencia: https://stackoverflow.com/questions/39817145/how-add-data-directly-to-the-arrayadapter

Este código no es vuestro, y no es correcto que os atribuyamos el mérito de su desarrollo.

**Comment by cybercamphackathon** [comment]
¿No lo corregís?

**Comment by UVaNoobs** [comment]
c9a94a906fb46f2fd409ed1d342c54fa6a087b0c

**Comment by cybercamphackathon** [comment]
Creo que el enlace no va al commit que me habeis enseñado.
De todos modos, como me lo habéis enseñado presencialmente, lo damos por cerrado.
