### ISSUE TITLE
No se maneja la excepción

### ISSUE THREAD

**Issue by cybercamphackathon** [UVaNoobs/BlueFingerprint#5]
https://github.com/UVaNoobs/BlueFingerprint/blob/0b8025ac0f59ed1fa41d5634cd67c73f1877f735/MainActivity.java#L307

Deberiais hacer un "raise" de la excepción correspondiente.
Tal cual está, la función podría devolver resultados inconsistentes.

**Comment by UVaNoobs** [comment]
Es cierto, pero actualmente no estamos utilizando dicho código.

**Comment by cybercamphackathon** [comment]
Perfecto.
